export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_TRUE = "AUTH_CHECK_TRUE";
export const AUTH_CHECK_FALSE = "AUTH_CHECK_FALSE";
// ko dung
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_FARMER_DATA = "FETCH_FARMER_DATA";
export const FETCH_ORDER_DATA = "FETCH_ORDER_DATA";
export const FETCH_LIST_USER_DATA = "FETCH_LIST_USER_DATA";
export const FETCH_COOPARE_DATA = "FETCH_COOPARE_DATA";
