//AUTHENTICATION
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
//search app react native
export const SEARCH_GUEST = "SEARCH_GUEST";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_TRUE = "AUTH_CHECK_TRUE";
export const AUTH_CHECK_FALSE = "AUTH_CHECK_FALSE";
// ko dung
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

//FARMER
export const FETCH_FARMER_DATA = "FETCH_FARMER_DATA";

//ORDER
export const FETCH_ORDER_DATA = "FETCH_ORDER_DATA";
export const PURCHASE_START = "PURCHASE_START";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAIL = "PURCHASE_FAIL";

//USER
export const FETCH_LIST_USER_DATA = "FETCH_LIST_USER_DATA";

//COOPERATE
export const FETCH_COOPARE_DATA = "FETCH_COOPARE_DATA";
export const FETCH__LIST_USER_ORDER = "FETCH__LIST_USER_ORDER";
//DIARY
export const FETCH_BATCH_LIST = "FETCH_BATCH_LIST";
export const FETCH_CHECK_MAP = "FETCH_CHECK_MAP";
